---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcrmyapp5
spec:
  replicas: 2
  selector:
   matchLabels:
    app: gcrmyapp5
  template:
    metadata:
      labels:
        app: gcrmyapp5
    spec:
      containers:
      - name: gcrmyapp5
        image: eu.gcr.io/asif-first-project/asifulla4/tomactimage:tagversion
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gcrmyapp5
  labels:
    app: gcrmyapp5
spec:
  type: LoadBalancer
  selector:
    app: gcrmyapp5
  ports:
  - protocol: TCP
    port: 6655
    targetPort: 8080
