---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp4
spec:
  replicas: 3
  selector:
   matchLabels:
    app: myapp4
  template:
    metadata:
      labels:
        app: myapp4
    spec:
      containers:
      - name: myapp4
        image: asifulla4/tomactimage::tagversion
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myapp4
  labels:
    app: myapp4
spec:
  type: LoadBalancer
  selector:
    app: myapp4
  ports:
  - protocol: TCP
    port: 5611
    targetPort: 8080
